/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/_authenticated/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/_authenticated/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/_authenticated/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/import': typeof AuthenticatedImportRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/import': typeof AuthenticatedImportRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/import' | '/insights' | '/trades' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/import' | '/insights' | '/trades' | '/'
  id:
    | '__root__'
    | '/_authenticated/import'
    | '/_authenticated/insights'
    | '/_authenticated/trades'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
